# Generated by Django 5.1 on 2024-11-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateField()),
                ('estado', models.CharField(max_length=100)),
                ('orden', models.IntegerField()),
                ('marca', models.CharField(max_length=50)),
            ],
        ),
    ]
