# Generated by Django 5.1 on 2024-11-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('ID_Venta', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('ID_Producto', models.CharField(max_length=6)),
                ('ID_Cliente', models.CharField(max_length=6)),
                ('Cantidad_vendida', models.IntegerField()),
                ('Precio_Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fecha_venta', models.DateField()),
                ('Metodo_Pago', models.CharField(max_length=50)),
            ],
        ),
    ]
