# Generated by Django 5.1 on 2024-11-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('idcliente', models.PositiveSmallIntegerField(max_length=6)),
                ('fecha_pedido', models.DateField()),
                ('estado', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodopago', models.CharField(max_length=50)),
                ('direccion_envio', models.CharField(max_length=100)),
            ],
        ),
    ]
